In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

### Load the data

In [2]:
dataset = pd.read_csv(r"C:\Data Science course\Guest Lectures\NLP 2 days master class\Day 1\twitter_training.csv",header= None)

In [3]:
dataset

0            1         2  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   
74681  9200       Nvidia  Positive   

                                                       3  
0      im getting on borderlands and i will murder yo...  
1      I am coming to the borders and I will kill you...  
2      im getting on borderlands and i will kill you ...  
3      im coming on borderlands and i will murder you...  
4      im getting on borderlands 2 and i will murder ...  
...                                                  ...  
74677  Just realized that the Windows partition of my...  
74678  Just realized that my Mac window partition is ...  
74679  Just realized the windows partition of my Mac ...  
74680  Just realized between the windows partition of...  
74681  Just like the windows partition of my Mac is l...  

[74682 rows x 4 columns]

In [4]:
dataset[2].value_counts()

Negative      22542
Positive      20832
Neutral       18318
Irrelevant    12990
Name: 2, dtype: int64

In [5]:
tweets = dataset.iloc[:,3:4]

In [6]:
tweets

3
0      im getting on borderlands and i will murder yo...
1      I am coming to the borders and I will kill you...
2      im getting on borderlands and i will kill you ...
3      im coming on borderlands and i will murder you...
4      im getting on borderlands 2 and i will murder ...
...                                                  ...
74677  Just realized that the Windows partition of my...
74678  Just realized that my Mac window partition is ...
74679  Just realized the windows partition of my Mac ...
74680  Just realized between the windows partition of...
74681  Just like the windows partition of my Mac is l...

[74682 rows x 1 columns]

In [7]:
tweets.columns = ["Tweets"]

In [8]:
tweets

Tweets
0      im getting on borderlands and i will murder yo...
1      I am coming to the borders and I will kill you...
2      im getting on borderlands and i will kill you ...
3      im coming on borderlands and i will murder you...
4      im getting on borderlands 2 and i will murder ...
...                                                  ...
74677  Just realized that the Windows partition of my...
74678  Just realized that my Mac window partition is ...
74679  Just realized the windows partition of my Mac ...
74680  Just realized between the windows partition of...
74681  Just like the windows partition of my Mac is l...

[74682 rows x 1 columns]

#### Text preprocessing

In [9]:
import re

In [10]:
re_special_char = "[^a-z\s]"

In [11]:
def text_preprocessing(review):
    review = str(review)
    #Normalizing the case 
    review = review.lower()
    #Removal of special characters
    review = re.sub(re_special_char,"", review)
    return review

In [12]:
tweets["Tweets"]  = tweets["Tweets"].apply(text_preprocessing)

In [13]:
tweets

Tweets
0      im getting on borderlands and i will murder yo...
1      i am coming to the borders and i will kill you...
2      im getting on borderlands and i will kill you all
3      im coming on borderlands and i will murder you...
4      im getting on borderlands  and i will murder y...
...                                                  ...
74677  just realized that the windows partition of my...
74678  just realized that my mac window partition is ...
74679  just realized the windows partition of my mac ...
74680  just realized between the windows partition of...
74681  just like the windows partition of my mac is l...

[74682 rows x 1 columns]

### Tokenization

In [14]:
import tensorflow as tf

In [15]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [16]:
tk = Tokenizer()

In [17]:
tk.fit_on_texts(tweets["Tweets"])

In [18]:
tk.word_index

{'the': 1,
 'i': 2,
 'to': 3,
 'and': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'for': 8,
 'in': 9,
 'this': 10,
 'it': 11,
 'you': 12,
 'on': 13,
 'my': 14,
 'that': 15,
 'with': 16,
 'game': 17,
 'so': 18,
 'me': 19,
 'have': 20,
 'just': 21,
 'but': 22,
 'not': 23,
 'are': 24,
 'be': 25,
 'all': 26,
 'was': 27,
 'at': 28,
 'its': 29,
 'im': 30,
 'like': 31,
 'out': 32,
 'from': 33,
 'your': 34,
 'now': 35,
 'get': 36,
 'we': 37,
 'as': 38,
 'they': 39,
 'has': 40,
 'if': 41,
 'one': 42,
 'do': 43,
 'good': 44,
 'about': 45,
 'can': 46,
 'play': 47,
 'no': 48,
 'will': 49,
 'an': 50,
 'really': 51,
 'when': 52,
 'love': 53,
 'new': 54,
 'up': 55,
 'what': 56,
 'more': 57,
 'time': 58,
 'by': 59,
 'how': 60,
 'some': 61,
 'people': 62,
 'or': 63,
 'johnson': 64,
 'why': 65,
 'see': 66,
 'shit': 67,
 'cant': 68,
 'dont': 69,
 'been': 70,
 'best': 71,
 'still': 72,
 'got': 73,
 'games': 74,
 'great': 75,
 'even': 76,
 'playing': 77,
 'who': 78,
 'because': 79,
 'xbox': 80,
 'fucking': 81,
 'go':

In [19]:
len(tk.word_index)

38492

In [20]:
tk.word_index["fantastic"]

682

In [21]:
tk.index_word[551]

'kinda'

In [22]:
tweets["Tweets"][600]

'well this is certainly a development'

In [23]:
token_list = tk.texts_to_sequences(["well this is certainly a development"])

In [24]:
token_list

[[160, 10, 7, 1296, 5, 1960]]

In [25]:
input_sequences = []

In [26]:
token_list = token_list[0]

In [27]:
token_list

[160, 10, 7, 1296, 5, 1960]

In [28]:
"well this is certainly a development"

'well this is certainly a development'

In [29]:
for i in range(1,len(token_list)-1):
    n_gram_seq = token_list[0:i+2]
    input_sequences.append(n_gram_seq)

In [30]:
token_list

[160, 10, 7, 1296, 5, 1960]

In [31]:
"well this is certainly a development"

'well this is certainly a development'

In [32]:
input_sequences

[[160, 10, 7],
 [160, 10, 7, 1296],
 [160, 10, 7, 1296, 5],
 [160, 10, 7, 1296, 5, 1960]]

In [33]:
def gen_sequences(data):
    input_seq = []
    for each_tweet in data:
        token_list = tk.texts_to_sequences([each_tweet])
        token_list = token_list[0]
        for i in range(1,len(token_list)-1):
            n_gram_seq = token_list[0:i+2]
            input_seq.append(n_gram_seq)
    return input_seq

In [34]:
input_sequences = gen_sequences(tweets["Tweets"])

In [35]:
input_sequences

[[30, 157, 13],
 [30, 157, 13, 123],
 [30, 157, 13, 123, 4],
 [30, 157, 13, 123, 4, 2],
 [30, 157, 13, 123, 4, 2, 49],
 [30, 157, 13, 123, 4, 2, 49, 1656],
 [30, 157, 13, 123, 4, 2, 49, 1656, 12],
 [30, 157, 13, 123, 4, 2, 49, 1656, 12, 26],
 [2, 100, 378],
 [2, 100, 378, 3],
 [2, 100, 378, 3, 1],
 [2, 100, 378, 3, 1, 6319],
 [2, 100, 378, 3, 1, 6319, 4],
 [2, 100, 378, 3, 1, 6319, 4, 2],
 [2, 100, 378, 3, 1, 6319, 4, 2, 49],
 [2, 100, 378, 3, 1, 6319, 4, 2, 49, 405],
 [2, 100, 378, 3, 1, 6319, 4, 2, 49, 405, 12],
 [2, 100, 378, 3, 1, 6319, 4, 2, 49, 405, 12, 26],
 [30, 157, 13],
 [30, 157, 13, 123],
 [30, 157, 13, 123, 4],
 [30, 157, 13, 123, 4, 2],
 [30, 157, 13, 123, 4, 2, 49],
 [30, 157, 13, 123, 4, 2, 49, 405],
 [30, 157, 13, 123, 4, 2, 49, 405, 12],
 [30, 157, 13, 123, 4, 2, 49, 405, 12, 26],
 [30, 378, 13],
 [30, 378, 13, 123],
 [30, 378, 13, 123, 4],
 [30, 378, 13, 123, 4, 2],
 [30, 378, 13, 123, 4, 2, 49],
 [30, 378, 13, 123, 4, 2, 49, 1656],
 [30, 378, 13, 123, 4, 2, 49, 1656

In [36]:
max_seq_len = max([len(seq) for seq in input_sequences])

In [37]:
max_seq_len

166

In [38]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [39]:
input_sequences = pad_sequences(input_sequences, maxlen = max_seq_len, padding='pre')

In [40]:
input_sequences

array([[   0,    0,    0, ...,   30,  157,   13],
       [   0,    0,    0, ...,  157,   13,  123],
       [   0,    0,    0, ...,   13,  123,    4],
       ...,
       [   0,    0,    0, ...,  494,   60,    2],
       [   0,    0,    0, ...,   60,    2,  284],
       [   0,    0,    0, ...,    2,  284, 2008]])

In [41]:
input_sequences.shape

(1185657, 166)

In [42]:
sliced_seq = input_sequences[0:100000,:]

In [43]:
sliced_seq

array([[   0,    0,    0, ...,   30,  157,   13],
       [   0,    0,    0, ...,  157,   13,  123],
       [   0,    0,    0, ...,   13,  123,    4],
       ...,
       [   0,    0,    0, ...,   29,   13,  975],
       [   0,    0,    0, ...,   13,  975, 1388],
       [   0,    0,    0, ...,  975, 1388,  183]])

In [44]:
sliced_seq.shape

(100000, 166)

In [45]:
X = sliced_seq[:,:-1]

In [46]:
X.shape

(100000, 165)

In [47]:
X

array([[   0,    0,    0, ...,    0,   30,  157],
       [   0,    0,    0, ...,   30,  157,   13],
       [   0,    0,    0, ...,  157,   13,  123],
       ...,
       [   0,    0,    0, ...,   79,   29,   13],
       [   0,    0,    0, ...,   29,   13,  975],
       [   0,    0,    0, ...,   13,  975, 1388]])

In [48]:
y = sliced_seq[:,-1]

In [49]:
y.shape

(100000,)

In [50]:
from tensorflow.keras.utils import to_categorical

In [51]:
y = to_categorical(y)

In [52]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [53]:
y.shape

(100000, 28286)

In [54]:
total_word = y.shape[1]

In [55]:
total_word

28286

### Build the Architecture

In [56]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Embedding, Dropout, Dense

#### Init the model

In [57]:
model = Sequential()

### Add Embedding layer

In [58]:
X.shape[1]

165

In [59]:
emb_layer = Embedding(total_word + 1, 100, input_length = X.shape[1])

In [60]:
model.add(emb_layer)

### Add the LSTM-1 Layer

In [61]:
#return_sequences -- True when we want to add another LSTM Layer after this
#return_sequences -- False -- When we are adding a Dense layer after LSTM
lstm_layer_1 = LSTM(kernel_initializer = "random_uniform", 
                    return_sequences = True ,units = 50 )

In [62]:
model.add(lstm_layer_1)

#### Add the LSTM-2 Layer

In [63]:
lstm_layer_2 = LSTM(kernel_initializer = "random_uniform", 
                    return_sequences = False ,units = 80 )

In [64]:
model.add(lstm_layer_2)

### Add the output layer

In [65]:
ouput_layer = Dense(kernel_initializer = "random_uniform", activation = "softmax", units = total_word)

In [66]:
model.add(ouput_layer)

In [67]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 165, 100)          2828700   
                                                                 
 lstm (LSTM)                 (None, 165, 50)           30200     
                                                                 
 lstm_1 (LSTM)               (None, 80)                41920     
                                                                 
 dense (Dense)               (None, 28286)             2291166   
                                                                 
Total params: 5,191,986
Trainable params: 5,191,986
Non-trainable params: 0
_________________________________________________________________


In [68]:
from tensorflow.keras.utils import plot_model

In [69]:
plot_model(model,show_shapes = True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model/model_to_dot to work.


In [70]:
model.compile(loss = "categorical_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [71]:
model.fit(X,y, epochs = 20, batch_size = 32)

Epoch 1/20
3125/3125 [==============================] - 456s 145ms/step - loss: 6.9638 - accuracy: 0.0409
Epoch 2/20
3125/3125 [==============================] - 445s 143ms/step - loss: 6.1588 - accuracy: 0.0781
Epoch 3/20
3125/3125 [==============================] - 502s 161ms/step - loss: 5.6154 - accuracy: 0.1145
Epoch 4/20
3125/3125 [==============================] - 457s 146ms/step - loss: 5.1387 - accuracy: 0.1451
Epoch 5/20
3125/3125 [==============================] - 487s 156ms/step - loss: 4.7220 - accuracy: 0.1780
Epoch 6/20
3125/3125 [==============================] - 460s 147ms/step - loss: 4.3553 - accuracy: 0.2167
Epoch 7/20
3125/3125 [==============================] - 465s 149ms/step - loss: 4.0303 - accuracy: 0.2588
Epoch 8/20
3125/3125 [==============================] - 464s 148ms/step - loss: 3.7483 - accuracy: 0.2990
Epoch 9/20
3125/3125 [==============================] - 509s 163ms/step - loss: 3.5058 - accuracy: 0.3365
Epoch 10/20
3125/3125 [=======================

## Save the model

In [76]:
model.save("Next_word_model.h5")

## save the tokenization

In [77]:
import joblib

In [78]:
joblib.dump(tk,"net_work_tk.pkl")

['net_work_tk.pkl']